// Generated by CoffeeScript 1.8.0
(function() {
  var CounterCache;

  CounterCache = (function() {
    function CounterCache() {
      this.cache = {};
      this.trackingCache = {};
    }

    CounterCache.prototype.flushToWithSource = function(queue) {
      var name, source, value, _results;
      _results = [];
      for (name in this.trackingCache) {
        for (source in this.trackingCache[name]) {
          value = this.trackingCache[name][source];
          queue.push({
            name: name,
            value: value,
            source: source
          });
        }
        _results.push(delete this.trackingCache[name]);
      }
      return _results;
    };

    CounterCache.prototype.increment = function(name, value) {
      var _base;
      if (value == null) {
        value = 1;
      }
      if ((_base = this.cache)[name] == null) {
        _base[name] = 0;
      }
      return this.cache[name] += value;
    };

    CounterCache.prototype.track = function(name, value, source) {
      var _base, _base1;
      if ((_base = this.trackingCache)[name] == null) {
        _base[name] = {};
      }
      if ((_base1 = this.trackingCache[name])[source] == null) {
        _base1[source] = 0;
      }
      return this.trackingCache[name][source] += value;
    };

    return CounterCache;

  })();

  module.exports = CounterCache;

}).call(this);

//# sourceMappingURL=counter_cache.js.map
